"""
src/tokenizer.py — Offline Local Tokenizer Wrapper
=====================================================
Wraps the HuggingFace ``tokenizers`` (Rust-backed) library to load all
artifacts from a local ``models/`` directory.

**Zero network calls are made at runtime.** The ``models/tokenizer.json``
artifact must be generated once via ``scripts/export_backbone.py``.

All output arrays are ``numpy.int64`` — the required dtype for ONNX Runtime
session inputs. The :meth:`encode_batch` method is used by the ``choice``
primitive to pack K option pairs into a single batched forward pass.

Design invariants:
    - Truncation is applied at :attr:`MAX_LENGTH` (512) — the DeBERTa-v3
      context window limit.
    - :meth:`encode` returns shape ``[1, seq_len]``.
    - :meth:`encode_batch` returns shape ``[N, seq_len]`` where ``seq_len``
      is the length of the longest sequence in the batch (dynamic padding).
    - Both methods return identical token IDs for the same input text
      (determinism guarantee).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
from tokenizers import Tokenizer  # type: ignore[import]


class GamanTokenizer:
    """
    Offline tokenizer that loads exclusively from a local ``models/`` directory.

    Uses the HuggingFace ``tokenizers`` Rust backend for maximum throughput.
    Produces numpy int64 arrays compatible with ONNX Runtime's expected input
    dtype — no conversion step needed between tokenization and inference.

    Attributes:
        MAX_LENGTH: Hard truncation limit matching DeBERTa-v3's maximum
                    context window of 512 tokens. Override by subclassing
                    or passing a custom ``models/tokenizer_config.json``.

    Example::

        tokenizer = GamanTokenizer()                         # load from models/
        encoded = tokenizer.encode("[STATE] key: val [QUERY] Is this safe?")
        # encoded["input_ids"].shape == (1, seq_len)

        batch = tokenizer.encode_batch(["text A", "text B"])
        # batch["input_ids"].shape == (2, max_seq_len_in_batch)
    """

    MAX_LENGTH: int = 512

    def __init__(self, models_dir: str | Path = "models") -> None:
        """
        Initialize the tokenizer from a local artifact directory.

        Args:
            models_dir: Path to the directory containing ``tokenizer.json``.
                        Generated by ``python scripts/export_backbone.py``.

        Raises:
            FileNotFoundError: If ``tokenizer.json`` is absent in
                               ``models_dir``. This signals that the export
                               script has not been run yet.
        """
        models_dir = Path(models_dir)
        tokenizer_path = models_dir / "tokenizer.json"

        if not tokenizer_path.exists():
            raise FileNotFoundError(
                f"Tokenizer artifact not found at '{tokenizer_path}'.\n"
                "  Generate it with:\n"
                "    python scripts/export_backbone.py\n"
                "  Then retry."
            )

        # Load the full tokenizer from the serialized JSON artifact.
        # For DeBERTa-v3, tokenizer.json embeds the SentencePiece model;
        # no separate spm.model file is needed at load time.
        self._tokenizer: Tokenizer = Tokenizer.from_file(str(tokenizer_path))

        # Truncate sequences that exceed the model's maximum context length.
        # Sequences shorter than MAX_LENGTH are unaffected.
        self._tokenizer.enable_truncation(max_length=self.MAX_LENGTH)

        # Enable dynamic padding: batches pad to the longest sequence.
        # Single-string encodes are unaffected (nothing to pad against).
        self._tokenizer.enable_padding()

    # ── Public API ────────────────────────────────────────────────────────────

    def encode(self, text: str, pair: str | None = None) -> dict[str, np.ndarray]:
        """
        Tokenize a single string or a (premise, hypothesis) sequence pair.

        Args:
            text: Main input sequence (e.g. premise / serialized state).
            pair: Optional second sequence (e.g. hypothesis / query). When provided,
                  outputs native [SEP] boundaries and token_type_ids (0 for text, 1 for pair).

        Returns:
            Dictionary with keys:
                - ``"input_ids"``      — shape ``[1, seq_len]``, dtype int64
                - ``"attention_mask"`` — shape ``[1, seq_len]``, dtype int64
                - ``"token_type_ids"`` — shape ``[1, seq_len]``, dtype int64

            ``seq_len`` is the actual (truncated) token count for this sequence.
        """
        if pair is not None:
            enc = self._tokenizer.encode(text, pair=pair)
        else:
            enc = self._tokenizer.encode(text)
        return self._wrap_single(enc)

    def encode_batch(
        self, inputs: list[str] | list[tuple[str, str]]
    ) -> dict[str, np.ndarray]:
        """
        Tokenize a batch of strings or (premise, hypothesis) pairs, dynamically
        padding to the longest sequence in the batch.

        Used by :meth:`GamanEngine.choice` to batch all K option pairs into
        a single ONNX forward pass (``batch_size = K``).

        Args:
            inputs: List of strings OR list of (text, pair) tuples.

        Returns:
            Dictionary with keys:
                - ``"input_ids"``      — shape ``[N, seq_len]``, dtype int64
                - ``"attention_mask"`` — shape ``[N, seq_len]``, dtype int64
                - ``"token_type_ids"`` — shape ``[N, seq_len]``, dtype int64

            where ``N = len(inputs)`` and ``seq_len`` = longest sequence length
            in the batch (all shorter sequences are zero-padded).
        """
        encs = self._tokenizer.encode_batch(inputs)
        return {
            "input_ids": np.array([e.ids for e in encs], dtype=np.int64),
            "attention_mask": np.array([e.attention_mask for e in encs], dtype=np.int64),
            "token_type_ids": np.array([e.type_ids for e in encs], dtype=np.int64),
        }

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _wrap_single(self, enc: Any) -> dict[str, np.ndarray]:
        """
        Wrap a single tokenizer Encoding as shape-``[1, seq_len]`` numpy arrays.

        Kept as a private method so :meth:`encode` stays readable and the
        array-construction logic is testable in isolation if needed.
        """
        return {
            "input_ids": np.array([enc.ids], dtype=np.int64),
            "attention_mask": np.array([enc.attention_mask], dtype=np.int64),
            "token_type_ids": np.array([enc.type_ids], dtype=np.int64),
        }
